from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_catalog():
    path = ROOT / "scripts/dependency_catalog.py"
    spec = importlib.util.spec_from_file_location("dependency_catalog_test", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_catalog_reads_central_nuget_and_actions() -> None:
    catalog = load_catalog()
    dependencies = catalog.collect(ROOT)
    names = {(item.ecosystem, item.name) for item in dependencies}
    assert ("nuget", "ModelContextProtocol") in names
    assert ("github-actions", "actions/checkout") in names


def test_generated_markdown_declares_its_scope() -> None:
    catalog = load_catalog()
    rendered = catalog.render_markdown(catalog.collect(ROOT))
    assert "does not claim that a version is the latest" in rendered
    assert "generated by scripts/dependency_catalog.py" in rendered
