"""Dependency-lock completeness and exact target selection contract."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from scripts.select_lock import SUPPORTED_LOCKS, lock_id, selected_lock

ROOT = Path(__file__).resolve().parents[1]
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}")
TARGETS = {
    ("linux", "x64", "3.12"): "linux-x64-py312",
    ("linux", "x64", "3.13"): "linux-x64-py313",
    ("linux", "x64", "3.14"): "linux-x64-py314",
    ("darwin", "arm64", "3.12"): "macos-arm64-py312",
    ("win32", "amd64", "3.12"): "windows-x64-py312",
}


def logical_requirements(text: str) -> list[str]:
    """Join pip-compile continuation lines into logical requirements."""
    lines: list[str] = []
    current = ""
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        current += (" " if current else "") + stripped.rstrip("\\").strip()
        if not stripped.endswith("\\"):
            lines.append(current)
            current = ""
    assert not current
    return lines


def expected_lock_paths() -> set[Path]:
    """Return every root and generated-project lock required by the matrix."""
    ids = set(TARGETS.values())
    root_locks = {ROOT / f"requirements-dev-{identifier}.lock" for identifier in ids}
    generator_root = ROOT / "skills/mcp-server-architect/locks"
    generator_locks = {
        generator_root / f"{kind}-{identifier}.lock" for kind in ("runtime", "dev") for identifier in ids
    }
    return root_locks | generator_locks


def test_every_committed_lock_is_expected_fully_pinned_and_hashed() -> None:
    committed = set(ROOT.glob("requirements-dev-*.lock")) | set(
        (ROOT / "skills/mcp-server-architect/locks").glob("*.lock")
    )
    assert committed == expected_lock_paths()
    for path in sorted(committed):
        text = path.read_text(encoding="utf-8")
        version_match = re.search(r"-py(3\d{2})\.lock$", path.name)
        assert version_match, path
        digits = version_match.group(1)
        assert f"autogenerated by pip-compile with Python {digits[0]}.{digits[1:]}" in text, path
        requirements = logical_requirements(text)
        assert requirements, path
        for requirement in requirements:
            assert "==" in requirement, (path, requirement)
            assert HASH.search(requirement), (path, requirement)
            assert " --hash=sha256:" in requirement, (path, requirement)


def test_selector_binds_os_architecture_and_python_version() -> None:
    assert SUPPORTED_LOCKS == {
        ("linux", "x64", "3.12"),
        ("linux", "x64", "3.13"),
        ("linux", "x64", "3.14"),
        ("macos", "arm64", "3.12"),
        ("windows", "x64", "3.12"),
    }
    for target, identifier in TARGETS.items():
        platform, architecture, version = target
        assert lock_id(platform, architecture, version) == identifier
        assert selected_lock(platform, architecture, version).name == f"requirements-dev-{identifier}.lock"

    for unsupported in (
        ("plan9", "x64", "3.12"),
        ("linux", "arm64", "3.12"),
        ("darwin", "x64", "3.12"),
        ("win32", "amd64", "3.13"),
        ("linux", "x64", "3.15"),
    ):
        with pytest.raises(RuntimeError):
            selected_lock(*unsupported)


def test_legacy_os_only_locks_are_not_published() -> None:
    legacy = {ROOT / f"requirements-dev-{platform}.lock" for platform in ("linux", "macos", "windows")}
    generator_root = ROOT / "skills/mcp-server-architect/locks"
    legacy |= {
        generator_root / f"{kind}-{platform}.lock"
        for kind in ("runtime", "dev")
        for platform in ("linux", "macos", "windows")
    }
    assert not any(path.exists() for path in legacy)
