#!/usr/bin/env python3
"""Generate a dependency catalog from manifests maintained by dependency bots."""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True, order=True)
class Dependency:
    ecosystem: str
    name: str
    version: str
    source: str
    kind: str = "direct"


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def scan_workflows(root: Path) -> Iterable[Dependency]:
    pattern = re.compile(r"^\s*-?\s*uses:\s*([^\s#]+)(?:\s*#\s*(.*))?$", re.M)
    for path in sorted((root / ".github" / "workflows").glob("*.y*ml")):
        for ref, comment in pattern.findall(path.read_text(encoding="utf-8")):
            if ref.startswith("./"):
                continue
            if "@" not in ref:
                continue
            name, version = ref.rsplit("@", 1)
            display = f"{version} ({comment.strip()})" if comment.strip() else version
            yield Dependency("github-actions", name, display, rel(path, root))


def scan_pyproject(root: Path) -> Iterable[Dependency]:
    for path in sorted(root.rglob("pyproject.toml")):
        if any(part in {".venv", "vendor", "build"} for part in path.parts):
            continue
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        project = data.get("project", {})
        for item in project.get("dependencies", []) or []:
            match = re.match(r"\s*([A-Za-z0-9_.-]+)\s*(.*)", item)
            if match:
                yield Dependency("pip", match.group(1), match.group(2).strip() or "unconstrained", rel(path, root))
        for group, items in (project.get("optional-dependencies", {}) or {}).items():
            for item in items:
                match = re.match(r"\s*([A-Za-z0-9_.-]+)\s*(.*)", item)
                if match:
                    yield Dependency("pip", match.group(1), match.group(2).strip() or "unconstrained", rel(path, root), f"optional:{group}")


def scan_nuget(root: Path) -> Iterable[Dependency]:
    for path in sorted(root.rglob("Directory.Packages.props")):
        tree = ET.parse(path)
        for element in tree.findall(".//PackageVersion"):
            name = element.attrib.get("Include") or element.attrib.get("Update")
            version = element.attrib.get("Version") or "unconstrained"
            if name:
                yield Dependency("nuget", name, version, rel(path, root), "central")
    for path in sorted(root.rglob("*.csproj")):
        if any(parent.name in {"obj", "bin"} for parent in path.parents):
            continue
        tree = ET.parse(path)
        for element in tree.findall(".//PackageReference"):
            name = element.attrib.get("Include")
            version = element.attrib.get("Version") or element.findtext("Version")
            if name and version:
                yield Dependency("nuget", name, version, rel(path, root))


def scan_npm(root: Path) -> Iterable[Dependency]:
    for path in sorted(root.rglob("package.json")):
        if "node_modules" in path.parts:
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for group in ("dependencies", "devDependencies", "peerDependencies"):
            for name, version in sorted((data.get(group) or {}).items()):
                yield Dependency("npm", name, str(version), rel(path, root), group)


def scan_docker(root: Path) -> Iterable[Dependency]:
    from_pattern = re.compile(r"^\s*FROM\s+([^\s]+)", re.I | re.M)
    for path in sorted(root.rglob("Dockerfile*")):
        if not path.is_file():
            continue
        for image in from_pattern.findall(path.read_text(encoding="utf-8")):
            if "@" in image:
                name, version = image.split("@", 1)
            elif ":" in image.rsplit("/", 1)[-1]:
                name, version = image.rsplit(":", 1)
            else:
                name, version = image, "latest/implicit"
            yield Dependency("docker", name, version, rel(path, root))


def collect(root: Path) -> list[Dependency]:
    dependencies = [
        *scan_workflows(root),
        *scan_pyproject(root),
        *scan_nuget(root),
        *scan_npm(root),
        *scan_docker(root),
    ]
    return sorted(set(dependencies))


def render_json(dependencies: list[Dependency]) -> str:
    return json.dumps({"schema_version": 1, "dependencies": [asdict(item) for item in dependencies]}, indent=2, sort_keys=True) + "\n"


def render_markdown(dependencies: list[Dependency]) -> str:
    lines = [
        "<!-- generated by scripts/dependency_catalog.py; do not edit -->",
        "# Dependency catalog",
        "",
        "This file reports versions declared in repository manifests. It does not claim that a version is the latest available.",
        "",
        "| Ecosystem | Dependency | Declared version/ref | Kind | Source |",
        "|---|---|---|---|---|",
    ]
    for item in dependencies:
        lines.append(f"| {item.ecosystem} | `{item.name}` | `{item.version}` | {item.kind} | `{item.source}` |")
    if not dependencies:
        lines.append("| — | — | — | — | No supported manifests found |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--json", type=Path, default=Path("docs/generated/dependency-catalog.json"))
    parser.add_argument("--markdown", type=Path, default=Path("docs/generated/dependency-catalog.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    json_path = root / args.json
    markdown_path = root / args.markdown
    dependencies = collect(root)
    expected = {json_path: render_json(dependencies), markdown_path: render_markdown(dependencies)}

    if args.check:
        stale = [path for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            for path in stale:
                print(f"stale generated dependency catalog: {path.relative_to(root)}", file=sys.stderr)
            return 1
        print(f"dependency catalog is current ({len(dependencies)} entries)")
        return 0

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        try:
            label = path.relative_to(root)
        except ValueError:
            label = path
        print(f"wrote {label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
