"""Reusable pure-logic helpers for MCP consumers."""

from .admission import AdmissionClass, AdmissionEvidence, classify_admission, mutation_allowed
from .consumer_contracts import HealthState, ProviderHealth, PublicResourceRef, verify_public_id_handoff
from .decision_engine import (
    CapabilityIdentity,
    CapabilityProfile,
    Decision,
    ErrorAction,
    ErrorStrategy,
    PaginationDecision,
    ResponseResult,
    Risk,
    TrustedCapabilityContract,
    TrustedCapabilityPolicy,
    TrustedPolicyBinding,
    UserIntent,
    choose_initial_detail_params,
    evaluate_decision,
    get_error_strategy,
    get_pagination_decision,
    handle_response,
    infer_capability_profile,
    select_efficient_tool,
    should_retry,
)
from .delivery_reconciliation import (
    DeliveryContext,
    DeliveryDecision,
    DeliveryState,
    ambiguous_transport_outcome,
    apply_authoritative_read_back,
    should_resend,
)
from .runtime_identity_ref import (
    RuntimeIdentityRef,
    runtime_instance_key,
    validate_runtime_identity_ref,
)

__all__ = [
    "AdmissionClass",
    "AdmissionEvidence",
    "CapabilityIdentity",
    "CapabilityProfile",
    "Decision",
    "DeliveryContext",
    "DeliveryDecision",
    "DeliveryState",
    "ErrorAction",
    "ErrorStrategy",
    "HealthState",
    "PaginationDecision",
    "ProviderHealth",
    "PublicResourceRef",
    "ResponseResult",
    "Risk",
    "RuntimeIdentityRef",
    "TrustedCapabilityContract",
    "TrustedCapabilityPolicy",
    "TrustedPolicyBinding",
    "UserIntent",
    "ambiguous_transport_outcome",
    "apply_authoritative_read_back",
    "choose_initial_detail_params",
    "classify_admission",
    "evaluate_decision",
    "get_error_strategy",
    "get_pagination_decision",
    "handle_response",
    "infer_capability_profile",
    "mutation_allowed",
    "runtime_instance_key",
    "select_efficient_tool",
    "should_resend",
    "should_retry",
    "validate_runtime_identity_ref",
    "verify_public_id_handoff",
]
